favicon: null
name: Gabriel DiMartino
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4375
  brandStrength: 1
  rhythmicContrast: 0.6936558547895402
  brandColors:
    - '#000000'
    - '#898886'
    - '#b3b3b3'
    - '#302f2b'
    - '#d5dadf'
  lightness: 0.375
typography_spectrum: 0.7048991865012795
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2204301
analytics:
  twitter: null
  google: null
  facebook: null
