name: Gabriel DiMartino
favicon: null
layout_spectrum: 0.543631715932861
typography_spectrum: 0.7048991865012795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.406768636777997
  lightness: 0.9602590778376907
  saturation: 0.43480045697651803
  rhythmicContrast: 0.6936558547895402
purpose: []
