name: Gabriel DiMartino
favicon: null
layout_spectrum: 0.2204301
typography_spectrum: 0.81601
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#898886'
    - '#b3b3b3'
    - '#302f2b'
    - '#d5dadf'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.6936558547895402
purpose: []
